require("plugin_configs.bufferline")
require("plugin_configs.cmp")
require("plugin_configs.colors")
require("plugin_configs.git")
require("plugin_configs.lsp-dap")
require("plugin_configs.lualine")
require("plugin_configs.telescope")
require("plugin_configs.treesitter")
